apiVersion: v1
kind: Service
metadata:
  name: notes-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    role: notes-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notes-frontend
  name: notes-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notes-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notes-frontend
        role: notes-frontend
    spec:
      containers:
        - env:
            - name: API_HOST
              value: localhost:30000
          image: dfrojas20/notes_frontend
          imagePullPolicy: IfNotPresent
          name: notes-frontend
          ports:
            - containerPort: 80
              protocol: http
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}