name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./notes_backend
        file: ./notes_backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes_backend:latest

    - name: build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./notes_frontend
        file: ./notes_frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes_backend:latest
