name: Test Microk8s
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: actions/checkout@v2         
    - uses: balchua/microk8s-actions@v0.3.2
      with:
        channel: '1.26/stable'
        addons: '["dns", "rbac", "hostpath-storage", "registry"]'
    - name: Setting up MicroK8s cluster
      id: myactions
      run: |
        kubectl get no
        kubectl get pods -A -o wide
        kubectl apply -f ./kubernetes/mongo-deployment.yaml
        sleep 40
        kubectl get pods -A -o wide
        kubectl exec mongo-0 -it -- mongo --eval 'rs.initiate({_id: "rs0", members: [{ _id: 0, host: "mongo-0.mongo:27017" }, { _id: 1, host: "mongo-1.mongo:27017" }, { _id: 2, host: "mongo-2.mongo:27017" }]})'
        kubectl exec mongo-0 -it -- mongo --eval 'rs.status()'
        kubectl apply -f ./kubernetes/back-deployment.yaml
        sleep 20
        kubectl apply -f ./kubernetes/front-deployment.yaml
        sleep 20
        kubectl get all -A -o wide
    - name: executing POST NOTE integration test
      run: |
        curl -X POST http://localhost:30000/notes \
        -H "Content-Type: application/json" \
        -d '{"title":"nota1", "content":"contenido1"}'
        kubectl exec mongo-0 -it -- mongo --eval 'db.notes.find()'
    - name: executing GET ALL NOTES integration test  
      run: |
          curl -X GET http://localhost:30000/notes \
          -H "Content-Type: application/json" \
    - name: executing frontend integration test
      run: |
        curl http://localhost:31000/ 
    - name: executing UPDATE NOTE integration test
      run: |
          curl -X PUT http://localhost:30000/notes?old_title=nota1&old_content=contenido1 \
          -H "Content-Type: application/json" \
          -d '{"title":"nota1acualizado", "content":"contenido1actualizado"}'
          kubectl exec mongo-0 -it -- mongo --eval 'db.notes.find()'
