name: Setup MicroK8s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-microk8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update system packages
        run: sudo apt-get update

      - name: Install Snapd
        run: sudo apt-get install -y snapd

      - name: Install MicroK8s
        run: sudo snap install microk8s --classic

      - run: GROUP=snap_microk8s 
      - run: sudo usermod -a -G $GROUP $USER
      - run: newgrp $GROUP
      - run: mkdir ~/.kube
      - run: sudo chown -f -R $USER ~/.kube
      - run: microk8s status

      - name: Display MicroK8s info
        run: microk8s kubectl get nodes
