name: Setup MicroK8s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-microk8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update system packages
        run: sudo apt-get update

      - name: Install Snapd
        run: sudo apt-get install -y snapd

      - name: Install MicroK8s
        run: sudo snap install microk8s --classic

      - name: Add current user to microk8s group
        run: |
         GROUP=snap_microk8s
         sudo usermod -a -G $GROUP $USER
         newgrp $GROUP
         mkdir ~/.kube
         sudo chown -f -R $USER ~/.kube

      - name: Verify MicroK8s installation
        run: microk8s status --wait-ready

      - name: Display MicroK8s info
        run: microk8s kubectl get nodes
